cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>', add, name='product_add'),
    path('remove/<int:product_id>', remove, name='product_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),  # !!!
    path('cart/', include('cart.urls')),  		# !!!
    path('coupon/', include('coupon.urls')),  # !!!
    path('order/', include('order.urls')),  # !!!
    path('', include('shop.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coupon/urls.py
from django.urls import path
from .views import add_coupon

app_name='coupon'

urlpatterns = [
    path('add/', add_coupon, name='add'),  # 쿠폰 추가
]

order/urls.py
from django.urls import path
from .views import *

app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('create_ajax/', OrderCreateAjaxView.as_view(),name='order_create_ajax'),
    path('checkout/', OrderCheckoutAjaxView.as_view(),name='order_checkout'),
    path('validation/', OrderImpAjaxView.as_view(),name='order_validation'),
    path('complete/', order_complete,name='order_complete'),
    path('admin/order/<int:order_id>/', admin_order_detail, name='admin_order_detail'),  # !!!
    path('admin/order/<int:order_id>/pdf/', admin_order_pdf, name='admin_order_pdf'),  # !!!
]

shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', product_in_category,
         name='product_all'),  		# 카테고리 지정 없이, 모든 상품을 조회
    # path('<slug:category_slug>/', product_in_category, # !!! 한글 슬러그 문제
    #      name='product_in_category'), # 카테고리 지정하여, 해당 상품을 조회
    path('<category_slug>/', product_in_category,
         name='product_in_category'),   # 카테고리 지정하여, 해당 상품을 조회
    path('<int:id>/<product_slug>/', product_detail,
         name='product_detail'),        # 상품 지정하여, 해당 상품을 조회
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


class AddProductForm(forms.Form):
    quantity = forms.IntegerField()
    is_update = forms.BooleanField(required=False, initial=False,
                                   widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from shop.models import Product
from .forms import AddProductForm
from .cart import Cart
from coupon.forms import AddCouponForm  # !!!


@require_POST
def add(request, product_id):  # 장바구니에 상품을 추가하는 뷰
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = AddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], is_update=cd['is_update'])
    return redirect('cart:detail')


def remove(request, product_id):  # 장바구니에서 지정한 상품을 삭제하는 뷰
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')


def detail(request):  # 장바구니 페이지 뷰
    cart = Cart(request)
    add_coupon = AddCouponForm()  # !!! AddCouponForm
    for product in cart:  # 장바구니에 담긴 상품마다 (수량 수정 가능하도록) AddProductForm 생성
        product['quantity_form'] = AddProductForm(
            initial={'quantity': product['quantity'], 'is_update': True}
        )
    return render(request, 'cart/detail.html', {'cart': cart, 'add_coupon': add_coupon})

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}   <!--load 명령은 extends 보다는 뒤에!!!-->
{% load humanize %} <!--load 명령은 extends 보다는 뒤에!!!-->

{% block title %}
    Shopping cart
{% endblock %}

{% block content %}
    <h3>Shopping cart</h3>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col" style="width: 25%;">Image</th>
                <th scope="col">Product</th>
                <th scope="col">Quantity</th>
                <th scope="col">Remove</th>
                <th scope="col">Unit price</th>
                <th scope="col">Price</th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}<!--with 명령-->
            <tr>
                <th scope="row">
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{{ product.image.url }}" class="img-thumbnail" style="max-height: 90%; max-width: 90%">
                    </a>
                </th>
                <td>{{ product.name }}</td>
                <td>
                    <form action="{% url 'cart:product_add' product.id %}" method="post">
                        {% csrf_token %}
                        {{ item.quantity_form.quantity }}
                        {{ item.quantity_form.is_update }}
                        <div class="row-fluid">
                            <input type="submit" class="btn btn-primary pull-right form-control" value="Update">
                        </div>
                    </form>
                </td>
                <td><a href="{% url 'cart:product_remove' product.id %}">Remove</a></td>
                <td class="num">&#8361;{{item.price | floatformat:'0' | intcomma}}</td>
                <td class="num">&#8361;{{item.total_price | floatformat:'0' | intcomma}}</td>
            </tr>
            {% endwith %}
        {% endfor %}
        <!-- tbody 내부에서 for 반복 끝나는 지점 밑에, 할인 전 총액과 쿠폰 관련 서브 토탈 행을 추가-->
        {% if cart.coupon %}  <!-- 카트에 쿠폰이 있을 경우에만 쿠폰 관련 할인 정보를 출력 -->
            <tr class="subtotal">
                <td>Subtotal</td>
                <td colspan="4"></td>
                <td >&#8361;{{cart.get_product_total | floatformat:'0' | intcomma}}</td>
            </tr>
            <tr>
                <td colspan="5">"{{ cart.coupon.code }}" coupon (&#8361;{{cart.coupon.amount | floatformat:'0' | intcomma}}) discounted</td>
                <td>&#8361;{{cart.get_discount_total | floatformat:'0' | intcomma}}</td>
            </tr>
        {% endif %}
            <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">&#8361;{{cart.get_total_price | floatformat:'0' | intcomma}}</td>
            </tr>
        </tbody>
    </table>
    <!-- table 닫는 태그 직후, 쿠폰 입력 폼을 추가-->
    <p>
        Add Coupon:
    </p>
    <form action='{% url "coupon:add" %}' method="post">
        {{ add_coupon }}
        <input type="submit" value="Add">
        {% csrf_token %}
    </form>

    <p class="text-right">
    <a href='{% url "shop:product_all" %}' class="btn btn-secondary">Continue shopping</a>
    <a href='{% url "orders:order_create" %}' class="btn btn-primary">Checkout</a> <!-- !!! -->
    </p>
{% endblock %}